Adds a working example of importing and building well known protos.
cgrushko/proto_library pull request #11
Opened 2018-02-05 11:35 UTC by erickj

Closes cgrushko/proto_library#10

2018-02-05 14:37 UTC, cgrushko requested changes
Nice! thanks a lot!
I'd like this to reach stackoverflow somehow; do you want to ask the question and immediately answer it?

2018-02-05 14:37 UTC, cgrushko commented on src/BUILD
> +        # `bazel query 'visible(//:*, kind(proto_library, @com_google_protobuf//:all))'`
Perhaps just `bazel query 'kind(proto_library, @com_google_protobuf//:all)'` ?

2018-02-06 09:33 UTC, erickj commented on src/BUILD
> +        # `bazel query 'visible(//:*, kind(proto_library, @com_google_protobuf//:all))'`
done

2018-02-06 09:33 UTC, erickj commented
sorry, I'm not used to the github review process... is there an equivalent of [PTAL](https://www.chromium.org/glossary)?

re: stack overflow - I'll try to address that later today when I have a moment and after the commit is integrated so that I can link to it.

2018-02-06 12:50 UTC, merged

2018-02-06 12:50 UTC, cgrushko commented
Thanks again for your contribution :)